### ISSUE TITLE
Error reading list on Sharepoint on premise

### ISSUE THREAD

**Issue by dromagnoli77** [vgrem/phpSPO#27]
Hi, I need to read listitem from a Sharepoint onpremise (not online), so I start from the example NtlmConnectExample.php and the authentication seems to work correctly.
When I try to read the items on the list I receive this error:
"Unknown Authentication Provider"

This is a snippet of my code:
try {
	$authCtx = new NtlmAuthenticationContext($Settings['Url'], $Settings['UserName'], $Settings['Password']);
	$authCtx->acquireTokenForUser($Settings['UserName'],$Settings['Password']);
    $ctx = new ClientContext($Settings['Url'],$authCtx);
	$listTitle = 'Tasks';
	$list = ensureList($ctx,$listTitle);
	//printTasks($list);
	//queryListViaCAMLQuery($list);
	generateTasks($list);
    //$itemId = createTask($list);
	//$item = getTask($list,$itemId);
	//updateTask($item);
    //deleteTask($item);
	//queryListItems($list);
}
catch (Exception $e) {
	echo 'Error: ',  $e->getMessage(), "\n";
}

How can i solve? Thanks

**Comment by frozenshadow** [comment]
Same problem here. Looks like this function is causing it not to work: https://github.com/vgrem/phpSPO/blob/master/src/runtime/auth/AuthenticationContext.php#L42

@vgrem is it possible to fix this?

**Comment by vgrem** [comment]
Hi there,

the issue with NtlmAuthenticationContext has been fixed.

**Comment by frozenshadow** [comment]
Thanks for the update @vgrem 

I used the following code to talk to a on premise server (SP 2010):

```PHP
try {
    $authCtx = new NtlmAuthenticationContext($Settings['Url'], $Settings['UserName'], $Settings['Password']);
	echo "You have been authenticated successfully \n";
    $ctx = new ClientContext($Settings['Url'],$authCtx);
    
    $listTitle = "Tasks" ;

    printListViews($ctx,$listTitle);
}
catch (Exception $e) {
    echo 'Error: ',  $e->getMessage(), "\n";
}

function printListViews(ClientContext $ctx,$listTitle){
    $list = $ctx->getWeb()->getLists()->getByTitle($listTitle);
    $views = $list->getViews();
    $ctx->load($views);
    $ctx->executeQuery();
    foreach( $views->getData() as $view ) {
        print "View title: '{$view->Title}'\r\n";
    }
}
```

However the problem still remains.

Am I doing something wrong here?

**Comment by vgrem** [comment]
Hi there,

`NtlmAuthenticationContext` is no longer available. It has been replaced with a more generic `NetworkCredentialContext `class which supports Basic & NTLM auth schemes.

Could you please confirm whether the following example for reading site properties for SharePoint On-Premises  is working (prints site url if succeeds ) for you?


	$authCtx = new \SharePoint\PHP\Client\NetworkCredentialContext($Settings['UserName'], $Settings['Password']);
	$authCtx->AuthType = CURLAUTH_NTLM; //NTML auth schema
	$ctx = new \SharePoint\PHP\Client\ClientContext($Settings['Url'],$authCtx);
	$site = $ctx->getSite();
	$ctx->load($site); //load site settings
	$ctx->executeQuery();
	print $site->getProperty("Url");


From  [NtlmConnectExample.php](https://github.com/vgrem/phpSPO/blob/master/examples/NtlmConnectExample.php)

**Comment by frozenshadow** [comment]
Thanks again for the update!

The authentication works seamlessly now. But I do not get back the site URL.

After some var dumping it appears that the library is trying to call the functions via /_api/.
This doesn't work for SharePoint 2010 because the REST API structure is different (https://msdn.microsoft.com/en-us/library/ff798339.aspx).

The whole library would basically need a rewrite to make it work with 2010 (...).
Way to much work, so I'll guess I stay with SOAP (unless you want to make the necessary adjustments off course  :stuck_out_tongue_winking_eye:).
